---

- name: Get Device Facts
  hosts: Junos
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  vars:
    netconf:
      host: "{{ inventory_hostname }}"

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Retrieving facts...
    junos_get_facts:  
      host={{ inventory_hostname }}
    register: junos

  - name: Facts
    debug: msg="{{ junos.facts }}"

  - name: Retrieve configuration...
    junos_get_config:  
      host: "{{ inventory_hostname }}"
      dest: "{{ inventory_hostname }}.xml"
      format: xml
      #provider: "{{ netconf }}"

  - name: load configure file into device
    junos_config:
      #host={{ inventory_hostname }}
      src: "{{ inventory_hostname }}.cfg"
      comment: update config
      provider: "{{ netconf }}"

  - name: Retrieving hostname...
    junos_get_facts:  
      host={{ inventory_hostname }}
    register: hostname

  - name: Hostname
    debug: msg="{{ hostname.facts.hostname }}"


